version: '3'

services:

  builder:

    build:

      args:
        UNAME_M: $HOSTTYPE

      context:
        ./ctx

    container_name:
      dev_xtru

    hostname:
      suitableapp

    volumes:
      - $PWD/init_container.sh:/usr/local/bin/init_container.sh:ro
      - $PWD:/home/xtru/xtru
      - $HOME/tns_admin:/opt/oracle/tns_admin:ro
      - $HOME/rpmbuild:/home/xtru/rpmbuild
      - $HOME/sa_home:/home/xtru/sa_home
      - $HOME/.gitconfig:/home/xtru/.gitconfig
